package com.danielius.uni.mybatis.model;

import java.util.List;

public class OptionalCourses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONAL_COURSES.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONAL_COURSES.TITLE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private String title;

    private List<Student> students;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONAL_COURSES.ID
     *
     * @return the value of PUBLIC.OPTIONAL_COURSES.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONAL_COURSES.ID
     *
     * @param id the value for PUBLIC.OPTIONAL_COURSES.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONAL_COURSES.TITLE
     *
     * @return the value of PUBLIC.OPTIONAL_COURSES.TITLE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONAL_COURSES.TITLE
     *
     * @param title the value for PUBLIC.OPTIONAL_COURSES.TITLE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setTitle(String title) {
        this.title = title;
    }
}