package com.danielius.uni.mybatis.model;

import java.util.List;

public class StudentGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_GROUP.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_GROUP.COURSE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private Integer course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_GROUP.SPECIALITY
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private String speciality;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_GROUP.ID
     *
     * @return the value of PUBLIC.STUDENT_GROUP.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public Long getId() {
        return id;
    }

    private List<Student> students;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_GROUP.ID
     *
     * @param id the value for PUBLIC.STUDENT_GROUP.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_GROUP.COURSE
     *
     * @return the value of PUBLIC.STUDENT_GROUP.COURSE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public Integer getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_GROUP.COURSE
     *
     * @param course the value for PUBLIC.STUDENT_GROUP.COURSE
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setCourse(Integer course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_GROUP.SPECIALITY
     *
     * @return the value of PUBLIC.STUDENT_GROUP.SPECIALITY
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_GROUP.SPECIALITY
     *
     * @param speciality the value for PUBLIC.STUDENT_GROUP.SPECIALITY
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }
}