package com.danielius.uni.mybatis.model;

import java.util.List;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    private Long groupId;


    private StudentGroup group;

    public List<OptionalCourses> getCourses() {
        return courses;
    }

    public void setCourses(List<OptionalCourses> courses) {
        this.courses = courses;
    }

    private List<OptionalCourses> courses;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.NAME
     *
     * @return the value of PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.NAME
     *
     * @param name the value for PUBLIC.STUDENT.NAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @return the value of PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.SURNAME
     *
     * @param surname the value for PUBLIC.STUDENT.SURNAME
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @return the value of PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.GROUP_ID
     *
     * @param groupId the value for PUBLIC.STUDENT.GROUP_ID
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }
}