package com.danielius.uni.mybatis.dao;

import com.danielius.uni.mybatis.model.OptionalCourses;
import com.danielius.uni.mybatis.model.Student;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface OptionalCoursesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONAL_COURSES
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONAL_COURSES
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int insert(OptionalCourses record);


    int insertStudents(@Param("student_id")Long st_id, @Param("course_id")Long oc_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONAL_COURSES
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    OptionalCourses selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONAL_COURSES
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    List<OptionalCourses> selectAll();

    List<Student> selectCourseStudents(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONAL_COURSES
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int updateByPrimaryKey(OptionalCourses record);
}