package com.danielius.uni.mybatis.dao;

import com.danielius.uni.mybatis.model.OptionalCourses;
import com.danielius.uni.mybatis.model.Student;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    List<Student> selectAll();
    List<Student> selectGroupStudents(Long id);

    List<OptionalCourses> selectOptionalCoursesForStudent(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int updateByPrimaryKey(Student record);
}