package com.danielius.uni.mybatis.dao;

import com.danielius.uni.mybatis.model.Student;
import com.danielius.uni.mybatis.model.StudentGroup;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface StudentGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_GROUP
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_GROUP
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int insert(StudentGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_GROUP
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    StudentGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_GROUP
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    List<StudentGroup> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_GROUP
     *
     * @mbg.generated Sun Apr 16 14:32:31 EEST 2023
     */
    int updateByPrimaryKey(StudentGroup record);
}